#!/bin/bash

polybar example &
#enable_tapping &
compton &
#panel &
/home/aditya/.fehbg
urxvt -name scr -bg "#121212" -e scr &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 0
bspc config window_gap   12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a URxvt:scr sticky=on state=floating hidden=on
